### ISSUE TITLE
add action for ceph-ansible

### ISSUE THREAD

**Issue by ivotron** [popperized/ceph#2]

**Comment by arshul** [comment]
I'd like to give this a try. Please could you explain this a bit.

**Comment by ivotron** [comment]
thanks @arshul! I just pushed a [new branch](https://github.com/popperized/ceph/tree/ansible-action) with WIP for this. It needs more tweaks and a README to be a "proper" github action. In general, we want it to end up working as the `deploy.sh` stage contained in [this repository](https://github.com/msouppe/Ceph/blob/master/pipelines/ceph/deploy.sh).

**Comment by arshul** [comment]
Ok, I can do this, I would now require push access to this repo also.

**Comment by arshul** [comment]
I have done some minor changes, can you have a look and tell me how can I proceed further, what needs to be done with `install.sh` and what should be added to `group_vars/` directory.

**Comment by ivotron** [comment]
superseded by systemslab/popper#597
